/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/users/{userId}/recent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * [뷰1] 최근 본 티켓 목록 조회
     * @description 특정 유저가 최근 본 티켓을 최신 순으로 조회합니다.
     */
    get: operations["getRecentHistories"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/tickets/{ticketId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * [뷰3] 티켓 상세 조회
     * @description 해당 티켓의 상세 정보를 조회합니다.
     */
    get: operations["getTicketDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events/{eventId}/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * [뷰2] 티켓 목록 조회
     * @description 지정된 행사와 연관된 티켓 목록을 조회합니다.
     */
    get: operations["getTicketList"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/events/top": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * [뷰1] 베스트 인기티켓 목록 조회
     * @description 사람들이 많이 조회한 행사를 조회수가 높은 순으로 반환합니다.
     */
    get: operations["getTopEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description 공통 응답 DTO */
    ApiResponseBodyHistoryListResponseVoid: {
      /** @description 해당 API의 성공 여부를 반환합니다. true면 성공, false면 실패입니다. */
      success?: boolean;
      /**
       * Format: int32
       * @description 해당 API의 HTTP 상태 코드입니다.
       */
      status?: number;
      /** @description 해당 API의 결과에 대한 상태 메시지입니다. */
      message?: string;
      /**
       * @description 해당 API 관련 커스텀 코드입니다. 도메인(3글자)-상태코드-순번 으로 이루어져 있습니다.
       * @example TIC_200_001
       */
      code?: string;
      data?: components["schemas"]["HistoryListResponse"];
      /** @description 해당 API의 data를 설명하는 meta data입니다. 페이지네이션 정보나, 에러 발생 시 에러 정보를 반환합니다. */
      meta?: Record<string, never>;
    };
    /** @description 최근 본 티켓 목록 DTO */
    HistoryListResponse: {
      /** @description 최근 본 티켓 목록 */
      histories?: components["schemas"]["HistoryResponse"][];
    };
    /** @description 최근 본 티켓 DTO */
    HistoryResponse: {
      /**
       * Format: int64
       * @description 관련된 행사 ID (뷰에서는 최근 본 티켓이라고 되어있는데, 행사에 들어가야 실제 티켓이 나와서 행사 ID를 보내드립니다.)
       */
      eventId?: number;
      /** @description 관련 행사 이름 */
      name?: string;
      /**
       * Format: date-time
       * @description 행사 일시
       */
      eventDate?: string;
    };
    /** @description 공통 응답 DTO */
    ApiResponseBodyTicketDetailResponseVoid: {
      /** @description 해당 API의 성공 여부를 반환합니다. true면 성공, false면 실패입니다. */
      success?: boolean;
      /**
       * Format: int32
       * @description 해당 API의 HTTP 상태 코드입니다.
       */
      status?: number;
      /** @description 해당 API의 결과에 대한 상태 메시지입니다. */
      message?: string;
      /**
       * @description 해당 API 관련 커스텀 코드입니다. 도메인(3글자)-상태코드-순번 으로 이루어져 있습니다.
       * @example TIC_200_001
       */
      code?: string;
      data?: components["schemas"]["TicketDetailResponse"];
      /** @description 해당 API의 data를 설명하는 meta data입니다. 페이지네이션 정보나, 에러 발생 시 에러 정보를 반환합니다. */
      meta?: Record<string, never>;
    };
    /** @description 티켓 상세 조회 시 해당 티켓의 행사 정보 DTO */
    EventResponse: {
      /**
       * Format: int64
       * @description 행사 ID
       * @example 1
       */
      id?: number;
      /**
       * @description 행사 대분류
       * @example 스포츠
       */
      mainCategory?: string;
      /**
       * @description 행사 소분류
       * @example 2025 프로야구 포스트 시즌
       */
      subCategory?: string;
      /**
       * @description 행사 이름
       * @example 한국시리즈 5차전 [대전]
       */
      name?: string;
      /**
       * Format: date-time
       * @description 행사 일시
       */
      date?: string;
      /**
       * @description 행사 장소
       * @example 한화 생명 볼파크
       */
      place?: string;
      /**
       * @description 행사 상세명
       * @example LG vs 한화
       */
      detailName?: string;
      /**
       * @description 베스트 랭킹 여부
       */
      isTopRankng?: boolean;
    };
    /** @description 티켓 상세 조회 시 해당 티켓의 좌석 정보 DTO */
    SeatResponse: {
      /**
       * Format: int64
       * @description 좌석 ID
       * @example 1
       */
      id?: number;
      /**
       * Format: int32
       * @description 좌석 구역
       * @example 507
       */
      area?: number;
      /**
       * Format: int32
       * @description 좌석 열 정보
       * @example 2
       */
      seatColumn?: number;
      /**
       * @description 좌석 유형
       * @example 외야지정석
       */
      seatType?: string;
      /** @description 해당 좌석 사진 s3 url. 1시간만 접근 가능한 이미지 링크를 보내드립니다! */
      seatImageUrl?: string;
    };
    /** @description 티켓 상세 조회 DTO */
    TicketDetailResponse: {
      /**
       * Format: int64
       * @description 티켓 ID
       * @example 1
       */
      id?: number;
      /**
       * Format: int64
       * @description 상품 번호
       * @example 9702343334630
       */
      productNumber?: number;
      event?: components["schemas"]["EventResponse"];
      seat?: components["schemas"]["SeatResponse"];
      /**
       * @description 티켓 보유 여부
       * @example true
       */
      status?: boolean;
      /**
       * Format: int32
       * @description 티켓 당 가격
       * @example 150000
       */
      pricePerTicket?: number;
      /**
       * Format: int32
       * @description 수량
       * @example 1
       */
      amount?: number;
      /**
       * Format: int32
       * @description 총 가격
       * @example 150000
       */
      totalPrice?: number;
      /**
       * Format: date-time
       * @description 등록 일시
       */
      createdAt?: string;
    };
    /** @description 공통 응답 DTO */
    ApiResponseBodyTicketListResponseVoid: {
      /** @description 해당 API의 성공 여부를 반환합니다. true면 성공, false면 실패입니다. */
      success?: boolean;
      /**
       * Format: int32
       * @description 해당 API의 HTTP 상태 코드입니다.
       */
      status?: number;
      /** @description 해당 API의 결과에 대한 상태 메시지입니다. */
      message?: string;
      /**
       * @description 해당 API 관련 커스텀 코드입니다. 도메인(3글자)-상태코드-순번 으로 이루어져 있습니다.
       * @example TIC_200_001
       */
      code?: string;
      data?: components["schemas"]["TicketListResponse"];
      /** @description 해당 API의 data를 설명하는 meta data입니다. 페이지네이션 정보나, 에러 발생 시 에러 정보를 반환합니다. */
      meta?: Record<string, never>;
    };
    /** @description 특정 행사와 관련된 티켓 목록 DTO */
    TicketListResponse: {
      /** @description 관련 티켓 목록 */
      tickets?: components["schemas"]["TicketResponse"][];
    };
    /** @description 티켓 목록 내부 정보 DTO */
    TicketResponse: {
      /**
       * Format: int64
       * @description 티켓 ID
       * @example 1
       */
      id?: number;
      /**
       * Format: date-time
       * @description 티켓 일시
       */
      date?: string;
      /**
       * @description 티켓 세부 이름
       * @example LG vs 한화
       */
      detailName?: string;
      /**
       * Format: int32
       * @description 티켓 구역
       * @example 507
       */
      area?: number;
      /**
       * Format: int32
       * @description 티켓 좌석 열번호
       * @example 2
       */
      seatColumn?: number;
      /**
       * @description 티켓 좌석 종류
       * @example 외야지정석
       */
      seatType?: string;
      /**
       * @description 티켓 좌석 위치
       * @example 통로
       */
      seatPosition?: string;
      /**
       * Format: int32
       * @description 수량
       * @example 1
       */
      amount?: number;
      /**
       * Format: int32
       * @description 한 매 가격
       * @example 150000
       */
      price?: number;
    };
    /** @description 공통 응답 DTO */
    ApiResponseBodyEventListResponseEventPageMetaResponse: {
      /** @description 해당 API의 성공 여부를 반환합니다. true면 성공, false면 실패입니다. */
      success?: boolean;
      /**
       * Format: int32
       * @description 해당 API의 HTTP 상태 코드입니다.
       */
      status?: number;
      /** @description 해당 API의 결과에 대한 상태 메시지입니다. */
      message?: string;
      /**
       * @description 해당 API 관련 커스텀 코드입니다. 도메인(3글자)-상태코드-순번 으로 이루어져 있습니다.
       * @example TIC_200_001
       */
      code?: string;
      data?: components["schemas"]["EventListResponse"];
      meta?: components["schemas"]["EventPageMetaResponse"];
    };
    /** @description 베스트 인기티켓 목록 DTO */
    EventListResponse: {
      /** @description 베스트 인기티켓 목록 */
      events?: components["schemas"]["EventResponse"][];
    };
    /** @description 베스트 인기티켓 목록 조회 시 페이지네이션 DTO */
    EventPageMetaResponse: {
      /**
       * Format: int32
       * @description 현재 페이지 값
       * @example 0
       */
      page?: number;
      /**
       * Format: int32
       * @description 현재 페이지 크기
       * @example 10
       */
      size?: number;
      /**
       * Format: int64
       * @description 전체 티켓 수
       * @example 20
       */
      totalElements?: number;
      /**
       * Format: int32
       * @description 전체 페이지 수. (totalPages - 1)까지 page 요청 가능
       * @example 2
       */
      totalPages?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getRecentHistories: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 유저 ID
         * @example 1
         */
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 최근 본 티켓 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyHistoryListResponseVoid"];
        };
      };
      /** @description 해당 유저가 없어 최근 본 티켓 목록 조회 실패 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyHistoryListResponseVoid"];
        };
      };
    };
  };
  getTicketDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /**
         * @description 조회할 티켓 ID
         * @example 1
         */
        ticketId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 티켓 상세 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyTicketDetailResponseVoid"];
        };
      };
      /** @description 해당 티켓 ID가 없어 티켓 상세 조회 실패 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyTicketDetailResponseVoid"];
        };
      };
    };
  };
  getTicketList: {
    parameters: {
      query?: {
        /**
         * @description 필터링할 날짜
         * @example 2025-10-31
         */
        date?: string;
      };
      header?: never;
      path: {
        /**
         * @description 조회할 이벤트 ID
         * @example 1
         */
        eventId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 티켓 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyTicketListResponseVoid"];
        };
      };
      /** @description 해당 이벤트 ID가 없어 티켓 목록 조회 실패 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyTicketListResponseVoid"];
        };
      };
    };
  };
  getTopEvents: {
    parameters: {
      query?: {
        /**
         * @description 조회할 페이지 순서. 엔드포인트에 명시하지 않고 요청할 경우 기본 값 0
         * @example 1
         */
        page?: number;
        /**
         * @description 한 번에 가져올 페이지 양. 엔드포인트에 명시하지 않고 요청할 경우 기본 값 1
         * @example 10
         */
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 베스트 인기티켓 목록 조회 성공 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBodyEventListResponseEventPageMetaResponse"];
        };
      };
    };
  };
}
